@uri = pipeline

###

GET {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

###

GET {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

{
    "select": [],
    "where": {
        "equals": {
            "target": "id",
            "expr": "bpfflowmon-1654169925"
        }
    }
}

###

POST {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

< ./db-pipeline.json

###

PUT {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

{
    
}

###

DELETE {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

{
    "where": {
        "equals": {
            "target": "partner",
            "expr": "cnit"
        }
    }
}
