### GUARD Platform (c) 2020
###
### agent:      aminer          guard-vdpi  lora-agent  pgafilter
### exec_env:   network-manager web-server  lora        backend-prod
### type
###   exec_env: bare-metal  container-docker    container-k8s   vm  cloud   application gateway mobile
###   network_link: multi-pnt   network-slice   pnt2pnt wifi    hosted
@uri = {{network_link_uri}}
@network_link_type = hosted

### Get info by type
GET {{cb_manager_endpoint}}/{{uri}}

{
    "select": [],
    "where": {
        "equals": {
            "target": "type_id",
            "expr": "{{network_link_type}}"
        }
    }
}
