apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: "nginx"
  namespace: kube-system
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: "k8s.io/ingress-nginx"