kind: Service
apiVersion: v1
metadata:
  name: akhq
  namespace: guardce
  labels:
    app: akhq
    app.kubernetes.io/component: akhq
    app.kubernetes.io/instance: akhq
    app.kubernetes.io/name: akhq
    app.kubernetes.io/part-of: guard
  annotations:
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: akhq
    deploymentconfig: akhq
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: akhq
  namespace: guardce
  labels:
    app: akhq
    app.kubernetes.io/component: akhq
    app.kubernetes.io/instance: akhq
    app.kubernetes.io/name: akhq
    app.kubernetes.io/part-of: guard
  annotations:
spec:
  host: akhq-guardce.apps.ocp4.italtel.com
  to:
    kind: Service
    name: akhq
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: akhq
  namespace: guardce
data:
  AKHQ_CONFIGURATION: |
    akhq:
      connections:
        docker-kafka-server:
          properties:
            bootstrap.servers: "kafka-headless.guardce.svc:9092"
          schema-registry:
            url: "http://schema-registry:8085"
          connect:
            - name: "connect"
              url: "http://connect:8083"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
  name: akhq
  namespace: guardce
  labels:
    app: akhq
    app.kubernetes.io/component: akhq
    app.kubernetes.io/instance: akhq
    app.kubernetes.io/name: akhq
    app.kubernetes.io/part-of: guard
    app.openshift.io/runtime: akhq
    app.openshift.io/runtime-namespace: guardce
    app.openshift.io/runtime-version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akhq
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: akhq
        deploymentconfig: akhq
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: akhq
          image: 'pierluca1/akhq:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: akhq
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        runAsUser: 1000
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

