oc delete -f zookeeper.yaml
oc delete -f mysql.yaml
oc delete -f idm.yaml
oc delete -f kafka-cluster.yaml
oc delete -f es-cluster.yaml
oc delete -f kibana.yaml
oc delete -f akhq.yaml
oc delete -f cb-manager.yaml
oc delete -f algo1.1.2.yaml 
oc delete -f algo1.2.yaml
oc delete -f smart-controller.yaml
oc delete -f logstash.yaml
oc delete -f security-dashboard.yaml
oc delete -f blockchain-connector.yaml
oc delete -f algo5.yaml
oc delete -f logdata-anomaly-miner.yaml
oc delete -f guard-starter.yaml
