- pipeline.id: data
  path.config: "/usr/share/logstash/pipeline/data.conf"
- pipeline.id: event
  path.config: "/usr/share/logstash/pipeline/event.conf"
- pipeline.id: dashboard
  path.config: "/usr/share/logstash/pipeline/dashboard.conf"  
