apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: cornelio.hopmann@wobcom.de # Or any real email registered with LE
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        matchLabels:
          use-nginx-solver: "true"
      http01:
        ingress:
          class: nginx
    - http01:
        ingress:
          class: nginx 

    # An empty 'selector' means that this solver matches all domains