# Install python/pip
FROM alpine:latest
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python && apk add jq docker-compose
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools && pip3 install kafka-python && apk add bash curl wget net-tools procps && pip3 install joblib
COPY simulate_data.py /tmp
COPY vdpi_output_13Apr21.log /tmp
COPY create_topics_openshift.py /tmp
COPY delete_topics_openshift.py /tmp
COPY mytopics.txt /tmp
RUN mkdir /opt/guard
COPY lcp /opt/guard/lcp
COPY commands /opt/guard/commands
ADD ./elasticsearch-backup-restore/ /opt/guard/elasticsearch-backup-restore
RUN pip3 install -r /opt/guard/elasticsearch-backup-restore/requirements.txt
ADD ./guard-platform/utils/request-api/cb-manager/ /opt/guard/cb-manager
ENV DOCKERVERSION=20.10.5
RUN curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKERVERSION}.tgz \
  && tar xzvf docker-${DOCKERVERSION}.tgz --strip 1 -C /usr/local/bin docker/docker \
  && rm docker-${DOCKERVERSION}.tgz
#RUN apk add --update --no-cache docker-compose
#RUN curl -L "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
ENTRYPOINT ["tail", "-f", "/dev/null"]
