apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: guard-cluster
  namespace: kafka
spec:
  kafka:
    version: 2.6.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: external
        port: 9094
        type: ingress
        tls: true
        authentication:
          type: scram-sha-512
        configuration:
          bootstrap:
            host: kafka-bootstrap.guard.heisenbug.net
          brokers:
          - broker: 0
            host: kafka-0.guard.heisenbug.net
          - broker: 1
            host: kafka-1.guard.heisenbug.net
          - broker: 2
            host: kafka-2.guard.heisenbug.net
          brokerCertChainAndKey:
            secretName: cert-kafka
            certificate: tls.crt
            key: tls.key
    authorization:
      type: simple
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.6"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 50Gi
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 25Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}

