---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: strimzi-kafka
  namespace: operator
spec:
  releaseName: strimzi-kafka
  chart:
    repository: https://strimzi.io/charts/
    name: strimzi-kafka-operator
    version: 0.20.0
  values:
    # Default values for strimzi-kafka-operator.
    # TODO: change to official release.
    # If you set `watchNamespaces` to the same value as ``.Release.Namespace` (e.g. `helm ... --namespace $NAMESPACE`),
    # the chart will fail because duplicate RoleBindings will be attempted to be created in the same namespace
    watchNamespaces: ["kafka"]
    watchAnyNamespace: false

    image:
      repository: strimzi
      name: operator
      tag: 0.20.0
    logLevel: INFO
    fullReconciliationIntervalMs: 120000
    operationTimeoutMs: 300000
    kubernetesServiceDnsDomain: cluster.local

    tolerations: []
    affinity: {}
    nodeSelector: {}

    # Docker images that operator uses to provision various components of Strimzi.  To use your own registry prefix the
    # repository name with your registry URL.
    # Ex) repository: registry.xyzcorp.com/strimzi/zookeeper
    zookeeper:
      image:
        repository: strimzi
        name: kafka
        tagPrefix: 0.20.0
    kafka:
      image:
        repository: strimzi
        name: kafka
        tagPrefix: 0.20.0
    kafkaConnect:
      image:
        repository: strimzi
        name: kafka
        tagPrefix: 0.20.0
    kafkaConnects2i:
      image:
        repository: strimzi
        name: kafka
        tagPrefix: 0.20.0
    topicOperator:
      image:
        repository: strimzi
        name: operator
        tag: 0.20.0
    userOperator:
      image:
        repository: strimzi
        name: operator
        tag: 0.20.0
    kafkaInit:
      image:
        repository: strimzi
        name: operator
        tag: 0.20.0
    tlsSidecarKafka:
      image:
        repository: strimzi
        name: kafka
        tagPrefix: 0.20.0
    tlsSidecarEntityOperator:
      image:
        repository: strimzi
        name: kafka
        tagPrefix: 0.20.0
    kafkaMirrorMaker:
      image:
        repository: strimzi
        name: kafka
        tagPrefix: 0.20.0
    kafkaBridge:
      image:
        repository: strimzi
        name: kafka-bridge
        tag: 0.18.0
    kafkaExporter:
      image:
        repository: strimzi
        name: kafka
        tagPrefix: 0.20.0
    jmxTrans:
      image:
        repository: strimzi
        name: jmxtrans
        tag: 0.20.0
    kafkaMirrorMaker2:
      image:
        repository: strimzi
        name: kafka
        tagPrefix: 0.20.0
    cruiseControl:
      image:
        repository: strimzi
        name: kafka
        tagPrefix: 0.20.0
    tlsSidecarCruiseControl:
      image:
        repository: strimzi
        name: kafka
        tagPrefix: 0.20.0
    resources:
      limits:
        memory: 384Mi
        cpu: 1000m
      requests:
        memory: 384Mi
        cpu: 200m
    livenessProbe:
      initialDelaySeconds: 10
      periodSeconds: 30
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 30

    # Override the docker image repository used by all Strimzi images
    imageRepositoryOverride: ""
    # Override the docker image tag used by all Strimzi images
    imageTagOverride: ""
    createGlobalResources: true
