version: '3.3'

services:
  consumer_example:
    image: guard/aaa/consumer_example:latest
    container_name: aa_module-consumer_example
    build:
      context: consumer_example
    command: ./dockerize -wait https://idp:10443 -skip-tls-verify -timeout 600s java -jar consumer.jar
    environment:
      KAFKA_BROKERS: "kafka1:9093"
      CLIENT_ID: "consumer_example"
      KAFKA_SECURITY_PROTOCOL: "SASL_SSL"
      KAFKA_SSL_TRUSTSTORE_LOCATION: "/var/private/ssl/truststore.jks"
      KAFKA_SSL_TRUSTSTORE_PASSWORD: "javacaps"
      KAFKA_SSL_KEYSTORE_LOCATION: "/var/private/ssl/consumer_example.jks"
      KAFKA_SSL_KEYSTORE_PASSWORD: "javacaps"
      KAFKA_SSL_KEY_PASSWORD: "javacaps"
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      OAUTH_SERVER_BASE_URI: "https://idp:10443/oauth2/"
      OAUTH_SERVER_TOKEN_ENDPOINT_PATH: "/token"
      OAUTH_SERVER_INTROSPECTION_ENDPOINT_PATH: "/introspect"
      OAUTH_SERVER_CLIENT_ID: "kafka-consumer-example"
      OAUTH_SERVER_CLIENT_SECRET: "aCpTfjcuVP9T3BgLD3s8LfXXOoMa"
      OAUTH_SERVER_GRANT_TYPE: "client_credentials"
      OAUTH_SERVER_SCOPES: "kafka:topic:test:describe kafka:topic:test:read kafka:group:foo:describe kafka:group:foo:read"
      OAUTH_SERVER_ACCEPT_UNSECURE_SERVER: "true"
    depends_on:
      - kafka1
      - idp
