@uri = instance/algorithm

###

GET {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

{
    "select": []
}

###


GET {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

{
    "select": [],
    "where": {
        "equals": {
            "target": "id",
            "expr": "cnit-ml-1"
        }
    }
}

###

POST {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

< ./db-inst-algorithm.json

###

PUT {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

{
    
}

###

DELETE {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

{
    "where": {
        "equals": {
            "target": "partner",
            "expr": "cnit"
        }
    }
}
