version: '3.3'

services:
    kafka_oauth_python:
        image: guard/aaa/kafka_oauth_python:latest
        container_name: aa_module-kafka_oauth_python
        build:
            context: kafka_oauth_python
        command: python producer.py
        environment:
            KAFKA_CONFIG_BOOTSTRAP_SERVERS: 10.0.0.7:9093
            KAFKA_CONFIG_CLIENT_ID: kafka-producer-example
            KAFKA_CONFIG_SECURITY_PROTOCOL: SASL_SSL
            KAFKA_CONFIG_SSL_CAFILE: truststore.pem
            KAFKA_CONFIG_SASL_MECHANISM: OAUTHBEARER
            OAUTH2_INSTANCE_1_CLIENT_ID: kafka-producer-example
            OAUTH2_INSTANCE_1_SECRET: iV8vTaWP_OH4pxBGoNVOV4rZOQ4a
            OAUTH2_INSTANCE_1_TOKEN_URI: https://10.0.0.7:10443/oauth2/token
            OAUTH2_INSTANCE_1_IDP_TLS: truststore.pem
            OAUTH2_INSTANCE_1_SCOPES: "kafka:topic:test:describe kafka:topic:test:write kafka:topic:test:create"
        depends_on:
            - kafka
            - idp
